version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/attendance-tracker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "nuget"
    directory: "/attendance-tracker/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
